name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      npm-cache-hit: ${{ steps.cache-npm.outputs.cache-hit }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Cache NPM Cache
        id: cache-npm
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace}}/.npm
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install Dependencies
        run: npm ci

      - name: Run Lint:Fix
        run: npm run lint:fix

      - name: Run Prettier
        run: npm run prettier

      - name: Lint Code
        run: npm run lint

      - name: Run Tests and Generate Coverage Report
        run: npm run test:coverage -- --ci

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: ./coverage/lcov-report

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  build:
    runs-on: ubuntu-latest
    needs: test # Only build the project if tests pass
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Cache NPM Cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace}}/.npm
          key: ${{ runner.os }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-cache-

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build
